version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
        threshold: 1000
  method-complexity:
    config:
      threshold: 6
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 500
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4

engines:
  duplication:
    enabled: false
    config:
      languages:
        javascript:
          mass_threshold: 65
